### PR TITLE
Add python packaging.

### PR DESCRIPTION
**Pull request by StefanUlbrich**
Installs headers via pip. Suitable for rapidly writing packages. Modified from the pybind11. Xtensor itself should be  packaged and dded as a dependency too.

### CODE REVIEW

**Comment by tdegeus** [comment]
I think this is a great idea, which I do in my shadow package as well : https://github.com/tdegeus/pyxtensor . What do others think ? @JohanMabille @SylvainCorlay @wolfv

**Comment by JohanMabille** [comment]
To sum up #96, the idea would be to keep this repo pure C++ and add a new repo (xtensor.py) that would contain the pure python stuff. The python package would vendor all dependencies (xtensor, xsimd and xtl). This would be consistent with what we do for the R and Julia bindings.

**Comment by tdegeus** [comment]
Makes sense @JohanMabille . Will be much easier to maintain and ship. So all for it!

**Comment by tdegeus** [comment]
Regarding the name `xtensor.py`, wouldn't the `.` cause problems e.g. in packaging?

**Comment by tdegeus** [comment]
Ah, it seems from other packages that you have experience with it. I will try to allocate some time for this soon

**Pull request closed without merging**
