### PR TITLE
Fix pytensor overload resolution in pybind11.

### PR DESCRIPTION
**Pull request by zhujun98**
As discussed in #178. 

@SylvainCorlay I am not sure whether this is a good solution.

### CODE REVIEW

**Comment by zhujun98** [comment]
I have no ideal why CI failed. Could someone have a look? Thank you!

**Comment by JohanMabille** [comment]
It looks like conda cannot find cmake on `conda-forge`. I retart the build to see if it was an incident of if there is something more serious.

**Comment by JohanMabille** [comment]
The root cause of the error on travis is the miniconda distribution we use is too old.
I'm upgrading to latest miniconda and more recent pybind11, once #205 has been merged, you can rebase on master and force push, this should fix your issues.

**Comment by zhujun98** [comment]
Thanks a lot! I will keep an eye on #205

**Comment by SylvainCorlay** [comment]
Thanks @zhujun98.

**Pull request merged**
